// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package oswee_acc_v1

/*
Oswee Accounting API
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protobuf "protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMessage struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{0}
}
func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (dst *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(dst, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type ListPartnerAccountsRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPartnerAccountsRequest) Reset()         { *m = ListPartnerAccountsRequest{} }
func (m *ListPartnerAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPartnerAccountsRequest) ProtoMessage()    {}
func (*ListPartnerAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{1}
}
func (m *ListPartnerAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPartnerAccountsRequest.Unmarshal(m, b)
}
func (m *ListPartnerAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPartnerAccountsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPartnerAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPartnerAccountsRequest.Merge(dst, src)
}
func (m *ListPartnerAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPartnerAccountsRequest.Size(m)
}
func (m *ListPartnerAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPartnerAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPartnerAccountsRequest proto.InternalMessageInfo

func (m *ListPartnerAccountsRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListPartnerAccountsResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPartnerAccountsResponse) Reset()         { *m = ListPartnerAccountsResponse{} }
func (m *ListPartnerAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPartnerAccountsResponse) ProtoMessage()    {}
func (*ListPartnerAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{2}
}
func (m *ListPartnerAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPartnerAccountsResponse.Unmarshal(m, b)
}
func (m *ListPartnerAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPartnerAccountsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPartnerAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPartnerAccountsResponse.Merge(dst, src)
}
func (m *ListPartnerAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPartnerAccountsResponse.Size(m)
}
func (m *ListPartnerAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPartnerAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPartnerAccountsResponse proto.InternalMessageInfo

func (m *ListPartnerAccountsResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListPartnerAccountsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListPartnerAccountsResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetPartnerAccountRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPartnerAccountRequest) Reset()         { *m = GetPartnerAccountRequest{} }
func (m *GetPartnerAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetPartnerAccountRequest) ProtoMessage()    {}
func (*GetPartnerAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{3}
}
func (m *GetPartnerAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPartnerAccountRequest.Unmarshal(m, b)
}
func (m *GetPartnerAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPartnerAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetPartnerAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPartnerAccountRequest.Merge(dst, src)
}
func (m *GetPartnerAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetPartnerAccountRequest.Size(m)
}
func (m *GetPartnerAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPartnerAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPartnerAccountRequest proto.InternalMessageInfo

func (m *GetPartnerAccountRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PartnerAccount struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartnerAccount) Reset()         { *m = PartnerAccount{} }
func (m *PartnerAccount) String() string { return proto.CompactTextString(m) }
func (*PartnerAccount) ProtoMessage()    {}
func (*PartnerAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{4}
}
func (m *PartnerAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartnerAccount.Unmarshal(m, b)
}
func (m *PartnerAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartnerAccount.Marshal(b, m, deterministic)
}
func (dst *PartnerAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartnerAccount.Merge(dst, src)
}
func (m *PartnerAccount) XXX_Size() int {
	return xxx_messageInfo_PartnerAccount.Size(m)
}
func (m *PartnerAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_PartnerAccount.DiscardUnknown(m)
}

var xxx_messageInfo_PartnerAccount proto.InternalMessageInfo

func (m *PartnerAccount) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PartnerAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PartnerAccount) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type CreatePartnerAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePartnerAccountRequest) Reset()         { *m = CreatePartnerAccountRequest{} }
func (m *CreatePartnerAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePartnerAccountRequest) ProtoMessage()    {}
func (*CreatePartnerAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{5}
}
func (m *CreatePartnerAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePartnerAccountRequest.Unmarshal(m, b)
}
func (m *CreatePartnerAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePartnerAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePartnerAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePartnerAccountRequest.Merge(dst, src)
}
func (m *CreatePartnerAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePartnerAccountRequest.Size(m)
}
func (m *CreatePartnerAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePartnerAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePartnerAccountRequest proto.InternalMessageInfo

func (m *CreatePartnerAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdatePartnerAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePartnerAccountRequest) Reset()         { *m = UpdatePartnerAccountRequest{} }
func (m *UpdatePartnerAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePartnerAccountRequest) ProtoMessage()    {}
func (*UpdatePartnerAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{6}
}
func (m *UpdatePartnerAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePartnerAccountRequest.Unmarshal(m, b)
}
func (m *UpdatePartnerAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePartnerAccountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePartnerAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePartnerAccountRequest.Merge(dst, src)
}
func (m *UpdatePartnerAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePartnerAccountRequest.Size(m)
}
func (m *UpdatePartnerAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePartnerAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePartnerAccountRequest proto.InternalMessageInfo

func (m *UpdatePartnerAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RenamePartnerAccountRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenamePartnerAccountRequest) Reset()         { *m = RenamePartnerAccountRequest{} }
func (m *RenamePartnerAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RenamePartnerAccountRequest) ProtoMessage()    {}
func (*RenamePartnerAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{7}
}
func (m *RenamePartnerAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenamePartnerAccountRequest.Unmarshal(m, b)
}
func (m *RenamePartnerAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenamePartnerAccountRequest.Marshal(b, m, deterministic)
}
func (dst *RenamePartnerAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenamePartnerAccountRequest.Merge(dst, src)
}
func (m *RenamePartnerAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RenamePartnerAccountRequest.Size(m)
}
func (m *RenamePartnerAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenamePartnerAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenamePartnerAccountRequest proto.InternalMessageInfo

func (m *RenamePartnerAccountRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RenamePartnerAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RenamePartnerAccountResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenamePartnerAccountResponse) Reset()         { *m = RenamePartnerAccountResponse{} }
func (m *RenamePartnerAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RenamePartnerAccountResponse) ProtoMessage()    {}
func (*RenamePartnerAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{8}
}
func (m *RenamePartnerAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenamePartnerAccountResponse.Unmarshal(m, b)
}
func (m *RenamePartnerAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenamePartnerAccountResponse.Marshal(b, m, deterministic)
}
func (dst *RenamePartnerAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenamePartnerAccountResponse.Merge(dst, src)
}
func (m *RenamePartnerAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RenamePartnerAccountResponse.Size(m)
}
func (m *RenamePartnerAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenamePartnerAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenamePartnerAccountResponse proto.InternalMessageInfo

func (m *RenamePartnerAccountResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RenamePartnerAccountResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RenamePartnerAccountResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type DeletePartnerAccountRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePartnerAccountRequest) Reset()         { *m = DeletePartnerAccountRequest{} }
func (m *DeletePartnerAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePartnerAccountRequest) ProtoMessage()    {}
func (*DeletePartnerAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_0804428cb6fc6638, []int{9}
}
func (m *DeletePartnerAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePartnerAccountRequest.Unmarshal(m, b)
}
func (m *DeletePartnerAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePartnerAccountRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePartnerAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePartnerAccountRequest.Merge(dst, src)
}
func (m *DeletePartnerAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePartnerAccountRequest.Size(m)
}
func (m *DeletePartnerAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePartnerAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePartnerAccountRequest proto.InternalMessageInfo

func (m *DeletePartnerAccountRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "oswee.acc.v1.PingMessage")
	proto.RegisterType((*ListPartnerAccountsRequest)(nil), "oswee.acc.v1.ListPartnerAccountsRequest")
	proto.RegisterType((*ListPartnerAccountsResponse)(nil), "oswee.acc.v1.ListPartnerAccountsResponse")
	proto.RegisterType((*GetPartnerAccountRequest)(nil), "oswee.acc.v1.GetPartnerAccountRequest")
	proto.RegisterType((*PartnerAccount)(nil), "oswee.acc.v1.PartnerAccount")
	proto.RegisterType((*CreatePartnerAccountRequest)(nil), "oswee.acc.v1.CreatePartnerAccountRequest")
	proto.RegisterType((*UpdatePartnerAccountRequest)(nil), "oswee.acc.v1.UpdatePartnerAccountRequest")
	proto.RegisterType((*RenamePartnerAccountRequest)(nil), "oswee.acc.v1.RenamePartnerAccountRequest")
	proto.RegisterType((*RenamePartnerAccountResponse)(nil), "oswee.acc.v1.RenamePartnerAccountResponse")
	proto.RegisterType((*DeletePartnerAccountRequest)(nil), "oswee.acc.v1.DeletePartnerAccountRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingClient is the client API for Ping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingClient interface {
	SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, "/oswee.acc.v1.Ping/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServer is the server API for Ping service.
type PingServer interface {
	SayHello(context.Context, *PingMessage) (*PingMessage, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.acc.v1.Ping/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SayHello(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.acc.v1.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ping_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// PartnerAccountsClient is the client API for PartnerAccounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PartnerAccountsClient interface {
	ListPartnerAccounts(ctx context.Context, in *ListPartnerAccountsRequest, opts ...grpc.CallOption) (*ListPartnerAccountsResponse, error)
	GetPartnerAccount(ctx context.Context, in *GetPartnerAccountRequest, opts ...grpc.CallOption) (*PartnerAccount, error)
	CreatePartnerAccount(ctx context.Context, in *CreatePartnerAccountRequest, opts ...grpc.CallOption) (*PartnerAccount, error)
	UpdatePartnerAccount(ctx context.Context, in *UpdatePartnerAccountRequest, opts ...grpc.CallOption) (*PartnerAccount, error)
	RenamePartnerAccount(ctx context.Context, in *RenamePartnerAccountRequest, opts ...grpc.CallOption) (*RenamePartnerAccountResponse, error)
	DeletePartnerAccount(ctx context.Context, in *DeletePartnerAccountRequest, opts ...grpc.CallOption) (*protobuf.Empty, error)
}

type partnerAccountsClient struct {
	cc *grpc.ClientConn
}

func NewPartnerAccountsClient(cc *grpc.ClientConn) PartnerAccountsClient {
	return &partnerAccountsClient{cc}
}

func (c *partnerAccountsClient) ListPartnerAccounts(ctx context.Context, in *ListPartnerAccountsRequest, opts ...grpc.CallOption) (*ListPartnerAccountsResponse, error) {
	out := new(ListPartnerAccountsResponse)
	err := c.cc.Invoke(ctx, "/oswee.acc.v1.PartnerAccounts/ListPartnerAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAccountsClient) GetPartnerAccount(ctx context.Context, in *GetPartnerAccountRequest, opts ...grpc.CallOption) (*PartnerAccount, error) {
	out := new(PartnerAccount)
	err := c.cc.Invoke(ctx, "/oswee.acc.v1.PartnerAccounts/GetPartnerAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAccountsClient) CreatePartnerAccount(ctx context.Context, in *CreatePartnerAccountRequest, opts ...grpc.CallOption) (*PartnerAccount, error) {
	out := new(PartnerAccount)
	err := c.cc.Invoke(ctx, "/oswee.acc.v1.PartnerAccounts/CreatePartnerAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAccountsClient) UpdatePartnerAccount(ctx context.Context, in *UpdatePartnerAccountRequest, opts ...grpc.CallOption) (*PartnerAccount, error) {
	out := new(PartnerAccount)
	err := c.cc.Invoke(ctx, "/oswee.acc.v1.PartnerAccounts/UpdatePartnerAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAccountsClient) RenamePartnerAccount(ctx context.Context, in *RenamePartnerAccountRequest, opts ...grpc.CallOption) (*RenamePartnerAccountResponse, error) {
	out := new(RenamePartnerAccountResponse)
	err := c.cc.Invoke(ctx, "/oswee.acc.v1.PartnerAccounts/RenamePartnerAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAccountsClient) DeletePartnerAccount(ctx context.Context, in *DeletePartnerAccountRequest, opts ...grpc.CallOption) (*protobuf.Empty, error) {
	out := new(protobuf.Empty)
	err := c.cc.Invoke(ctx, "/oswee.acc.v1.PartnerAccounts/DeletePartnerAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerAccountsServer is the server API for PartnerAccounts service.
type PartnerAccountsServer interface {
	ListPartnerAccounts(context.Context, *ListPartnerAccountsRequest) (*ListPartnerAccountsResponse, error)
	GetPartnerAccount(context.Context, *GetPartnerAccountRequest) (*PartnerAccount, error)
	CreatePartnerAccount(context.Context, *CreatePartnerAccountRequest) (*PartnerAccount, error)
	UpdatePartnerAccount(context.Context, *UpdatePartnerAccountRequest) (*PartnerAccount, error)
	RenamePartnerAccount(context.Context, *RenamePartnerAccountRequest) (*RenamePartnerAccountResponse, error)
	DeletePartnerAccount(context.Context, *DeletePartnerAccountRequest) (*protobuf.Empty, error)
}

func RegisterPartnerAccountsServer(s *grpc.Server, srv PartnerAccountsServer) {
	s.RegisterService(&_PartnerAccounts_serviceDesc, srv)
}

func _PartnerAccounts_ListPartnerAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartnerAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAccountsServer).ListPartnerAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.acc.v1.PartnerAccounts/ListPartnerAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAccountsServer).ListPartnerAccounts(ctx, req.(*ListPartnerAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAccounts_GetPartnerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartnerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAccountsServer).GetPartnerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.acc.v1.PartnerAccounts/GetPartnerAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAccountsServer).GetPartnerAccount(ctx, req.(*GetPartnerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAccounts_CreatePartnerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePartnerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAccountsServer).CreatePartnerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.acc.v1.PartnerAccounts/CreatePartnerAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAccountsServer).CreatePartnerAccount(ctx, req.(*CreatePartnerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAccounts_UpdatePartnerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartnerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAccountsServer).UpdatePartnerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.acc.v1.PartnerAccounts/UpdatePartnerAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAccountsServer).UpdatePartnerAccount(ctx, req.(*UpdatePartnerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAccounts_RenamePartnerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenamePartnerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAccountsServer).RenamePartnerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.acc.v1.PartnerAccounts/RenamePartnerAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAccountsServer).RenamePartnerAccount(ctx, req.(*RenamePartnerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAccounts_DeletePartnerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePartnerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAccountsServer).DeletePartnerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.acc.v1.PartnerAccounts/DeletePartnerAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAccountsServer).DeletePartnerAccount(ctx, req.(*DeletePartnerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PartnerAccounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.acc.v1.PartnerAccounts",
	HandlerType: (*PartnerAccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPartnerAccounts",
			Handler:    _PartnerAccounts_ListPartnerAccounts_Handler,
		},
		{
			MethodName: "GetPartnerAccount",
			Handler:    _PartnerAccounts_GetPartnerAccount_Handler,
		},
		{
			MethodName: "CreatePartnerAccount",
			Handler:    _PartnerAccounts_CreatePartnerAccount_Handler,
		},
		{
			MethodName: "UpdatePartnerAccount",
			Handler:    _PartnerAccounts_UpdatePartnerAccount_Handler,
		},
		{
			MethodName: "RenamePartnerAccount",
			Handler:    _PartnerAccounts_RenamePartnerAccount_Handler,
		},
		{
			MethodName: "DeletePartnerAccount",
			Handler:    _PartnerAccounts_DeletePartnerAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_0804428cb6fc6638) }

var fileDescriptor_api_0804428cb6fc6638 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x51, 0x6f, 0xda, 0x30,
	0x10, 0xc7, 0x07, 0x43, 0x13, 0xdc, 0x26, 0xd0, 0xbc, 0x3c, 0x64, 0x0e, 0x93, 0xa6, 0x3c, 0x4c,
	0x80, 0xb6, 0x4c, 0xb0, 0x4f, 0xc0, 0xda, 0xaa, 0x55, 0xd5, 0x4a, 0x28, 0xa8, 0x0f, 0x55, 0x1f,
	0xa8, 0x49, 0xae, 0x51, 0x2a, 0x48, 0xd2, 0xd8, 0xb4, 0xe2, 0x0b, 0xf7, 0x73, 0x54, 0x49, 0x43,
	0x4b, 0x5c, 0x27, 0xa4, 0x12, 0x6f, 0xf6, 0xf9, 0x7f, 0xf7, 0xbf, 0xb3, 0x7f, 0x32, 0xb4, 0x58,
	0xe4, 0x5b, 0x51, 0x1c, 0x8a, 0x90, 0x7c, 0x09, 0xf9, 0x03, 0xa2, 0xc5, 0x1c, 0xc7, 0xba, 0x1f,
	0x52, 0x2d, 0x0d, 0xce, 0x57, 0x37, 0x7f, 0x71, 0x19, 0x89, 0xf5, 0xb3, 0xc6, 0xec, 0xc3, 0xe7,
	0x89, 0x1f, 0x78, 0xe7, 0xc8, 0x39, 0xf3, 0x90, 0x50, 0x68, 0x7a, 0x31, 0xa2, 0xf0, 0x03, 0x4f,
	0xaf, 0xfd, 0xac, 0xf5, 0x5a, 0xf6, 0xcb, 0xde, 0xfc, 0x0d, 0xf4, 0xcc, 0xe7, 0x62, 0xc2, 0x62,
	0x11, 0x60, 0x3c, 0x76, 0x9c, 0x70, 0x15, 0x08, 0x6e, 0xe3, 0xdd, 0x0a, 0xb9, 0x20, 0x6d, 0xa8,
	0xfb, 0x6e, 0x9a, 0xf3, 0xd1, 0xae, 0xfb, 0xae, 0x79, 0x0d, 0x86, 0x52, 0xcd, 0xa3, 0x30, 0xe0,
	0x28, 0xcb, 0x09, 0x81, 0x46, 0xc0, 0x96, 0xa8, 0xd7, 0x53, 0xd3, 0x74, 0x4d, 0x7e, 0x00, 0x38,
	0x31, 0x32, 0x81, 0xee, 0x8c, 0x09, 0xbd, 0x93, 0x9e, 0xb4, 0xb2, 0xc8, 0x58, 0x98, 0x03, 0xd0,
	0x8f, 0x51, 0x32, 0x28, 0xea, 0x66, 0x0a, 0xed, 0xbc, 0x70, 0x1f, 0x0d, 0x0c, 0xc1, 0x38, 0x48,
	0x37, 0xea, 0x1e, 0x36, 0x15, 0x6b, 0xaf, 0x15, 0x93, 0x94, 0x8b, 0xc8, 0x7d, 0x57, 0xca, 0x18,
	0x0c, 0x1b, 0x93, 0x55, 0xa5, 0x49, 0x55, 0x73, 0x98, 0x0c, 0xba, 0xea, 0x12, 0xfb, 0x7b, 0x8c,
	0x3f, 0x60, 0x1c, 0xe2, 0x02, 0x45, 0xb5, 0x2e, 0x47, 0xa7, 0xd0, 0x48, 0xb0, 0x23, 0xff, 0xa1,
	0x39, 0x65, 0xeb, 0x13, 0x5c, 0x2c, 0x42, 0xf2, 0xdd, 0xda, 0xe6, 0xd5, 0xda, 0xc2, 0x92, 0x16,
	0x1f, 0x99, 0x1f, 0x46, 0x8f, 0x0d, 0xe8, 0x48, 0x98, 0x91, 0x5b, 0xf8, 0xa6, 0xa0, 0x8f, 0xf4,
	0xf2, 0x75, 0x8a, 0x71, 0xa6, 0xfd, 0x0a, 0xca, 0xec, 0xf6, 0x2e, 0xe1, 0xeb, 0x1b, 0x0e, 0xc9,
	0xaf, 0x7c, 0x7e, 0x11, 0xa8, 0xb4, 0x2b, 0x4d, 0x96, 0xaf, 0x32, 0x03, 0x4d, 0x45, 0x18, 0x91,
	0xba, 0x2b, 0xa1, 0x70, 0xb7, 0x81, 0x8a, 0x47, 0xd9, 0xa0, 0x84, 0xd9, 0x1d, 0x06, 0x4b, 0xd0,
	0x54, 0xe8, 0xc9, 0x06, 0x25, 0x84, 0xd3, 0x41, 0x15, 0x69, 0xf6, 0x16, 0x57, 0xa0, 0xa9, 0x30,
	0x94, 0xed, 0x4a, 0x50, 0xa5, 0x7a, 0x26, 0xdd, 0x7c, 0x97, 0x89, 0xfe, 0x28, 0xf9, 0x31, 0xe7,
	0x9f, 0xd2, 0xd0, 0xbf, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0x52, 0xc8, 0x2d, 0x63, 0x05,
	0x00, 0x00,
}
